services:
  postgres:
    container_name: english_exercise
    image: postgres:18-alpine
    environment:
      POSTGRES_DB: english_exercise_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "6003:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
